name: Google Lighthouse

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    paths-ignore:
      - ".vscode/**"
      - "_headers"
  pull_request:
    paths-ignore:
      - ".vscode/**"
      - "_headers"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@v2
        with:
            egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          # Python 3.7 is latest supported on CF
          python-version: 3.7
          check-latest: true
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: MkDocs cache
        uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: mkdocs build
        env:
            CARDS: true
      - uses: actions/upload-artifact@v3
        with:
          name: site
          path: ${{ github.workspace }}/site/
          if-no-files-found: error
  lhci:
    name: Lighthouse
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        settings-formFactor: [mobile, desktop]
        include:
          # # Using iPhone 14 size https://blisk.io/devices/details/iphone-14
          - settings-formFactor: mobile
            settings-screenEmulation-width: 390
            settings-screenEmulation-height: 844
            settings-screenEmulation-deviceScaleFactor: 3
            settings-screenEmulation-mobile: true
          - settings-formFactor: desktop
            settings-screenEmulation-width: 1920
            settings-screenEmulation-height: 1080
            settings-screenEmulation-deviceScaleFactor: 1
            settings-screenEmulation-mobile: false
    steps:
      - uses: step-security/harden-runner@v2
        with:
          disable-sudo: true
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          check-latest: true
      - run: npm install -D @lhci/cli@latest
      - run: npx lhci collect --settings.formFactor ${{ matrix.settings-formFactor }} --settings.screenEmulation.width ${{ matrix.screenEmulation-width }} --settings.screenEmulation.height ${{ matrix.screenEmulation-height }} --settings.screenEmulation.deviceScaleFactor ${{ matrix.screenEmulation-deviceScaleFactor }} --settings.screenEmulation.mobile ${{ matrix.screenEmulation-mobile }}
      - run: npx lhci assert
      - run: npx lhci upload --githubStatusContextSuffix /${{ matrix.settings-formFactor }}
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}